# Building a Java project
language: java

# We can specify a list of JDKs to be used for testing
jdk:
- openjdk11

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
provider: releases
file_glob: true
skip_cleanup: true
api_key: $jeddie
file:
- .travis.yml
on:
tags: true
branch: tag
repo: jeddie23/Travis_CI_Tutorial

notifications:
email:
-1257582342@qq.com
